### ISSUE TITLE
I used your EFI, but I'll have a black screen during installation

### ISSUE THREAD

**Issue by li33114413** [thefiredragon/MacOS-XPS-9500-4K-OpenCore#1]
10875H-64G-1650Ti-1200P screen

**Comment by thefiredragon** [comment]
1200P means 3k Panel? 
Same Comet Lake area? 
Read about that 3k needs different 4k patch or try without patching EDID.

**Comment by thefiredragon** [comment]
https://translate.google.de/translate?hl=de&sl=zh-CN&tl=en&u=http%3A%2F%2Fbbs.pcbeta.com%2Fviewthread-1873385-1-1.html&prev=search

**Comment by li33114413** [comment]
1K panel, I using @zachs78 EFI without this question

**Comment by thefiredragon** [comment]
Okay, good to hear, this repo is for 4k devices.
