### ISSUE TITLE
Recovery mode not working.

### ISSUE THREAD

**Issue by ultraCAO** [thefiredragon/MacOS-XPS-9500-4K-OpenCore#11]
I try using the boot menu to boot into recovery mode. it booted through the apple logo screen then to the grey screen where the cursor is working but nothing else is loaded. any idea?
I wanted to disable SIP to delete a monitor overwrite in read-only file system.

**Comment by thefiredragon** [comment]
For recovery you need to add under nvram prev-lang:kbd en-US:0

**Comment by thefiredragon** [comment]
https://dortania.github.io/OpenCore-Install-Guide/config.plist/skylake.html#nvram
