### ISSUE TITLE
Grey with mouse arrow

### ISSUE THREAD

**Issue by masterbater** [thefiredragon/MacOS-XPS-9500-4K-OpenCore#12]
I am now at wits end brother
Disable all the settings on bios according to zac github
Bought 970 evo plus, bought another xpg 8200 pro. Remove the micron ssd.
I generated smbios the only change I made on config.plist
Change sata to ACHI
I cfg unlock and verify it says unlock
My config is i7-10750H, 16gb ram 4k touch 15 inch

I booted with your efi after loading mac logo, there is only arrow and grey background, I enable apple debug and applepanic and it shows a UI of macos installation cannot be completed. 
Same as zach and thewaterdragon efi.

But did update my bios before I was trying to make a hackintosh
Can you share to me what is your bios version brother.

**Comment by thefiredragon** [comment]
Could you provide pictures of your issue?
I‘ll commit later an update.

**Comment by masterbater** [comment]
![Uploading Screenshot_20210308-035508_Video Player.jpg…]()

**Comment by masterbater** [comment]
![Uploading Screenshot_20210308-035508_Video Player.jpg…]()
`

**Comment by masterbater** [comment]
![Screenshot_20210308-035508_Video Player](https://user-images.githubusercontent.com/26339988/110252915-a72c1880-7fc2-11eb-8881-cfb463693617.jpg)
Here bro, hope you could help me with the issue thanks

**Comment by thefiredragon** [comment]
First please use My repo only with xps 9500 4K touch 
Your efi can‘t reognize config plist, opencore changed bootstrap with the latest Version, i‘ll commit it here later, please only add with opencore configurator your smbios Infos 16,4 , with your plist something Went wrong

**Comment by thefiredragon** [comment]
So I updated, please create correctly an installer, and use updated repo, only add smbios values, this should work fine. best Regards

**Comment by masterbater** [comment]
![20210308_045807](https://user-images.githubusercontent.com/26339988/110254655-fbd39180-7fca-11eb-9625-ae6cef104f0f.jpg)
Thanks bro Ill try the new efi. I believe we have the exact same specs

**Comment by thefiredragon** [comment]
yes, we have, :)

**Comment by thefiredragon** [comment]
You Said something like setup is grey with mouse? 

You Need also to add under nvram for setup a keyboard language, take a look under my Last closed issue here about recovery, there i posted the value

**Comment by masterbater** [comment]
Thanks a lot bro, I managed to get it work by resetting the bios
