### ISSUE TITLE
Questions about updated config.plist (Generic section and EDID Patch)

### ISSUE THREAD

**Issue by kaeltis** [thefiredragon/MacOS-XPS-9500-4K-OpenCore#14]
Hi,

first of all, thanks a lot for this awesome setup, it's working really well on my XPS and without your repo I most definitely wouldn't be running macOS on it since it just takes so much time figuring out what exactly to tweak where to make things work.

With the latest update I noticed two things changed and I wasn't really sure on how to proceed with them, maybe you can help me here:

- In 1d500b8029709200f421cf901e7cc10734532113 you removed the `Generic` section from the config with things like Serial and UUID, does this need to be added again by the user or is this now somehow automatically generated by OpenCore?
- In bea58ac034726b289ff4a1648a2f27871d0332c8 you added an EDID under `PciRoot(0x0)/Pci(0x2,0x0)` with `#AAPL00,override-no-connect` - does this mean the EDID patch is now required again? Do we need to replace this with our own EDID or should it be the same for all XPS 9500 4K models?

**Comment by thefiredragon** [comment]
I removed serial ‚cause I used this for my machine. You need to generate your own serial.

Edid patch is not needed at this time.

**Comment by kaeltis** [comment]
Thanks!
