### ISSUE TITLE
Can you advise how to modify for non 4k

### ISSUE THREAD

**Issue by aghil4u** [thefiredragon/MacOS-XPS-9500-4K-OpenCore#16]
Can you please? I'm getting grey screen after apple logo

**Comment by thefiredragon** [comment]
Which processor your machine conatain?
Please comment out enable-max-pixel-clock-override or delete this from config.plist

Grey screen means you need to add a Keyboard language for the installer.


NVRAM -> Add -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 -> prev-lang:kbd

by default is "ru-RU:252" should probably be "en-US:0" for Americans.
