### ISSUE TITLE
Non 4k display

### ISSUE THREAD

**Issue by paddyjoneill** [thefiredragon/MacOS-XPS-9500-4K-OpenCore#2]
I'm having problems with the EFI and wondering if it's to do with the display. I've created the installer usb and I get the Apple logo but then a screen flicker and black screen. Which version of open core is this using?

**Comment by thefiredragon** [comment]
Do you have a 4k Display? When not try other repos,
It's latest opencore 6.3 

Also did you use latest bios?

Von meinem iPhone gesendet

**Comment by thefiredragon** [comment]
For non4k repo you need other settings remove ssdt-i2c this ones not capable with non 4k touch 

Von meinem iPhone gesendet
