### ISSUE TITLE
Is this useful for the sleep

### ISSUE THREAD

**Issue by sweet3c** [thefiredragon/MacOS-XPS-9500-4K-OpenCore#20]
use the latest BIOS hardware
https://www.dell.com/support/kbdoc/en-us/000129843/windows-10-troubleshooting-sleep-hibernation-issues-on-your-dell-pc?lang=en

**Comment by thefiredragon** [comment]
Did you test it with a last bios update ?

**Comment by thefiredragon** [comment]
@sweet3c bump

**Comment by thefiredragon** [comment]
Is not working with new bios.
