### ISSUE TITLE
Gray screen with mouse pointer - language dialog not shown

### ISSUE THREAD

**Issue by theojalba** [thefiredragon/MacOS-XPS-9500-4K-OpenCore#21]
Got a copy of this repo and:

1. Disabled the right items in the BIOS.
2. Added the `NVRAM > Platform Info > Generic` section with the GenSMBIOS serials. 
2. Disabled CFGLock. 

But was stuck on a gray screen with a moving mouse pointer.

Based on a discussion thread online I figured out that the installer was stuck before the language selection dialog. The issue is that NVRAM > 7C436110-AB2A-4BBB-A880-FE41995C9F82 > prev-lang:kbd needs to be changed from `string` to `data`. Once that's done the language selection dialog is shown and the installer is unstuck.

Can you make this change in the repo? Sometimes ProperTree will not update the data type on save, so it may need to be done manually with a text editor like SublimeText.

```
<key>prev-lang:kbd</key>
<data></data>
```

Dortania says either `data` or `string` is ok, but in my experience only `data` works. Other repos for MacOS-XPS-9500 use `data`.

Lastly, thank you for your excellent work in putting together this repo. It's the only one compatible with BigSur and it's a huge time saver.

**Comment by thefiredragon** [comment]
I‘ll add this by next update,
This was also discussed in an closed thread here , :)

**Comment by theojalba** [comment]
Eh, this is confusing... open issues are issues that are not currently fixed -- while closed issues are issues that are either invalid or fixed. It seems that you are keeping your own private list of fixed and unfixed issues.

Most people who cannot get this running will click issues and see open issues only -- closed issues are in a separate hidden section.

Just my 2 cents.

**Comment by thefiredragon** [comment]
I push updates soon, that this mistake and mishandle not follow up.
People should not Run into this issue, you are right. Sry
