### ISSUE TITLE
Wi-Fi not working at all

### ISSUE THREAD

**Issue by DylanAkp** [thefiredragon/MacOS-XPS-9500-4K-OpenCore#23]
Zach's with Catalina works fine, in installer and system

But this one doesn't work for Wi-Fi (at least for me) either the installer and the system once installed with some manipulations.

**Comment by thefiredragon** [comment]
Which wifi card do you use?
Theres a beta issue also that usb 2 Devices not work under monterey, when u use this repo Download itwlm kext depending on your installed System pls

**Comment by DylanAkp** [comment]
AX1650
I'ver installed the right driver and now everything works
