### ISSUE TITLE
Bad battery life

### ISSUE THREAD

**Issue by ton-An** [thefiredragon/MacOS-XPS-9500-4K-OpenCore#24]
Hey!

I installed your EFI (Big Sur version) but the battery life is quite bad. Only 1:30hrs max. I've tried quite a lot but couldn't fix it. It also happens on all other 9500 EFI's I could find.

I think it has something to do with the chipset as it can get quite hot while running mac os. Everything else (e.g. the CPU) behaves normally.

It seems to me that this is a Dell related issue. A user on tonymacx who owns the 7590 seems to have had the same issue: https://www.tonymacx86.com/threads/dell-xps-15-7590-power-management-battery-life-problems.299015/

![Screen Shot 2021-10-22 at 12 10 11](https://user-images.githubusercontent.com/25333824/138445121-4532d41a-1282-4c3b-9342-4e1aaa846b57.png)
![Screen Shot 2021-10-22 at 12 08 15](https://user-images.githubusercontent.com/25333824/138445123-938e49ff-6b03-435c-ac5a-4633e0b712a8.png)

**Comment by zspherez** [comment]
I've also disabled the touchscreen in BIOS, having the same issues with very short battery life. @ton-An did you ever get this figured out?

**Comment by ton-An** [comment]
Well, I'm still on it. At least kinda.

The reason is that the Nvidia isn't turned off. Normally you can call the ssdt _OFF method of the gpu but there just doesn't seem to be one. At least, I couldn't find it. Tho, the _PS3 method exists. This method puts the gpu into the lowest power state. Using this method, I get about 4 hours with everything on maximum power saving. So, it's still half of Windows' battery life. Not great but better.

This is the file which utilizes the _PS3 method: https://github.com/zachs78/MacOS-XPS-9500-OpenCore/blob/master/EFI/OC/ACPI/SSDT-NoHybGfx.aml

**Comment by zspherez** [comment]
Interesting. Is this just a problem with Monterey, as it seems like the battery life is significantly shorter since upgrading. That said, I will stick that into my EFI and see what it does in terms of battery life. I wonder if this will also solve the overheating problems that some people are having?

**Comment by thefiredragon** [comment]
I had added DSDT to disable graphics.
I also had disabled this in bios,
