### ISSUE TITLE
WiFi stop working after 13112021

### ISSUE THREAD

**Issue by ultraCAO** [thefiredragon/MacOS-XPS-9500-4K-OpenCore#27]

**Comment by zspherez** [comment]
Make sure that you are using the correct AirportItlwm for your version. If you are still running into issues you can try my XPS repository on my profile.

**Comment by ultraCAO** [comment]
> Make sure that you are using the correct AirportItlwm for your version. If you are still running into issues you can try my XPS repository on my profile.

Thanks, Got it working. didn't know they have one for different versions of the os.
