### ISSUE TITLE
Stopped after 1st apple logo

### ISSUE THREAD

**Issue by waskojo** [thefiredragon/MacOS-XPS-9500-4K-OpenCore#3]
Thanks so far for sharing. As said in title I tried to install on 9500 4K i7 10750. Beside 1TB HD a 970 EVO is installed. Installation from zachs78 (Catalina) worked so far, exept card reader and touchscreen.  

Any hints?

**Comment by thefiredragon** [comment]
Stopping 1. Apple Logo is not a debug log, boot verbose and look up at the issue.
Did you patched well your display under linux? 
Try frist install macos with fake device-id or -igfxvesa

**Comment by waskojo** [comment]
Thanks for reply. Despite using  GensmBIOS  for adapting conig.plist I changend nothing from your files.  Is fake devie ID not included?

**Comment by thefiredragon** [comment]
You need to adjust my config with yoour patched edid from Linux

**Comment by waskojo** [comment]
Okay, thank you!  I work on this and com back here when its done. May I upload my file here?

**Comment by thefiredragon** [comment]
You dont need, each Display has a own edid, we don,'t want bricked devices.

Von meinem iPhone gesendet

**Comment by waskojo** [comment]
Thank you very much, in the meantime I have managed an it's working exept Cardreader? 

Just one minor hint: In linux it needs to be xrandr --props, there is one- missing.

Although its working now a few questions:  
You recommend to enter please note to adjust your PlatformInfo to MacBookPro 16.4. I havent done so far
If I add the platforminfo should the Syntax be  <key>PlatformInfo</MacBookPro 16.4> ? 

You recommend to enter please note to adjust your PlatformInfo to MacBookPro 16.4. I havent done. 
For the EDID I canged those two lines with my EDID. Correct? For me it seems, because its working, but not sure?
<key>AAPL00,override-no-connect</key>
				<data>AAAAAADeDQ0O</data>

Finally I guess that you are german, I am too.

Daher hier noch ein Dankeschön, dank deiner Arbeit habe ich nun einen coolen Rechner.
Nun muss ich noch versuchen den BootProzess vom Stick auf den Rechner übertragen,  gibt es da eine Hilfe? Ich glaube im Thread von @robotblox.  Nochmals Danke!

Viele Grüße Joerg

**Comment by thefiredragon** [comment]
xrandr --props is the correct way under linux, to help also other ones, its better to talk in english here.

Correct way: 
<string>MacBookPro16,4</string>
<key>SystemSerialNumber</key>

Note only with this the usb-controller will be correctly initialized.

For AAPL00,override-no-connect you need to enter your patched edid if you use a tool like openconfigurator, plist editor  in hex, if you use a normal editor in base64.
There was an issue, I wrote "Enter your edid here" but forgot to change data into string. So the values in this section are wrong provided from this repo.
So delete provided values and enter yours.

With the python script you get hex encoded and base64 encoded strings which you can use,
best Regards

**Comment by waskojo** [comment]
Thanks, using Batch Gensmbios I was able to setup with my own serial! Unfortunatly cardreader is still not working. It seems the rest is fine. 
Any advise?

**Comment by thefiredragon** [comment]
Till yet not
