### ISSUE TITLE
Keyboard issue: cmd + 1 = s, cmd + 2 = d, cmd + 3 = f, cmd + 4 = g

### ISSUE THREAD

**Issue by trongrg** [thefiredragon/MacOS-XPS-9500-4K-OpenCore#7]
As in the title, after I upgrade to Big Sur using this repo, I have problems with keyboard

I found out that I can't take screenshot with cmd + shift + 3, and then when I am in a textarea, cmd + shift + 3 types an F (just did it)

I tried to connect a usb keyboard and the combination works fine, taking screenshot instead of typing F

If anyone has any clue on how to solve this, it would be great

**Comment by thefiredragon** [comment]
I'll take a look next days

**Comment by thefiredragon** [comment]
Alt GR + shift + 3 works fine
